# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

            - name: GitHub Action for Standalone ESLint
  # You may pin to the exact commit or the version.
  # uses: 123FLO321/action-eslint-standalone@fc33f1337a4ad6d3396cc20adccfc22375ad9336
  uses: 123FLO321/action-eslint-standalone@1.0.0
          
