# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Swift

on:
  push:
    branches: [ "Secand" ]
  pull_request:
    branches: [ "Secand" ]

jobs:
  build:

    runs-on: macos-latest
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
          
